import { Command } from 'commander'
import chalk from 'chalk'
import path from 'path'
import fs from 'fs-extra'
import { Output } from '../utils/output'
import { handleError } from '../utils/errors'
import { KnowledgeBaseManager } from '../../core/KnowledgeBaseManager'
import { getSkillsSourcePath } from '../../utils/paths'
import {
  KB_TYPES,
  KB_STATUSES,
  KB_TYPE_PREFIXES,
  KB_RELATIONS,
  KB_WORK_TYPES,
  KB_KNOWLEDGE_TYPES,
  KB_REFERENCE_TYPES,
  KBTypeStrict,
  ValidationMode,
} from '../../models'

interface ValidationFlags {
  strict?: boolean
  draft?: boolean
}

function pickValidationMode(opts: ValidationFlags): ValidationMode | undefined {
  if (opts.strict) return 'strict'
  if (opts.draft) return 'draft'
  return undefined
}

function getKB(opts: ValidationFlags = {}): KnowledgeBaseManager {
  return new KnowledgeBaseManager(process.cwd(), {
    validation: pickValidationMode(opts),
  })
}

function requireInit(kb: KnowledgeBaseManager): boolean {
  if (!kb.isInitialized()) {
    Output.error('Knowledge Base not initialized. Run: orka kb init')
    return false
  }
  return true
}

export function kbCommand(program: Command) {
  const kb = program
    .command('kb')
    .description('Project knowledge base — track decisions, meetings, questions, and more')

  // --- init ---
  kb.command('init')
    .description('Initialize Knowledge Base in current project')
    .option('--skip-skills', 'Do not install Claude Code skills')
    .action(async (opts) => {
      try {
        const manager = getKB()

        if (manager.isInitialized()) {
          Output.warn('Knowledge Base already initialized')
          return
        }

        await manager.initialize()
        Output.success('Knowledge Base initialized in .orka-kb/')

        if (!opts.skipSkills) {
          await installSkills()
        }
      } catch (error) {
        handleError(error)
      }
    })

  // --- add ---
  kb.command('add <type> <title>')
    .description(`Add a new entity. Valid types: ${KB_TYPES.join(', ')}`)
    .option('-s, --status <status>', 'Entity status (default depends on type)')
    .option('-p, --property <kv...>', 'Properties as key=value pairs')
    .option('-t, --tag <tags...>', 'Tags')
    .option('-l, --link <links...>', 'Links as relation:target-id')
    .option('--strict', 'Reject on validation errors (clean v2 KBs)')
    .option('--draft', 'Allow validation issues, log as warnings (default)')
    .option('--actor <actor>', 'Actor for the event log (default: cli)')
    .option('--skill <name>', 'Mark this entity as generated by a skill — auto-creates activity + generated-by edge')
    .option('--session <id>', 'Optional session id for the skill run (used in activity properties)')
    .option('--json', 'Output as JSON')
    .action(async (type, title, opts) => {
      try {
        const manager = getKB(opts)
        if (!requireInit(manager)) return

        const properties: Record<string, unknown> = {}
        if (opts.property) {
          for (const kv of opts.property) {
            const [key, ...rest] = kv.split('=')
            properties[key] = rest.join('=')
          }
        }

        const edges: Array<{ relation: string; target: string }> = []
        if (opts.link) {
          for (const link of opts.link) {
            const [relation, target] = link.split(':')
            if (relation && target) {
              edges.push({ relation, target })
            }
          }
        }

        // Default status: first valid status for the type, or 'active'
        const defaultStatus =
          (KB_STATUSES as Record<string, readonly string[]>)[type]?.[0] ?? 'active'

        let entity
        if (opts.skill) {
          entity = await manager.addEntityFromSkill(opts.skill, type, title, {
            status: opts.status ?? defaultStatus,
            properties,
            tags: opts.tag || [],
            edges,
            actor: opts.actor || `skill:${opts.skill}`,
          })
        } else {
          entity = await manager.addEntity(type, title, {
            status: opts.status ?? defaultStatus,
            properties,
            tags: opts.tag || [],
            edges,
            actor: opts.actor,
          })
        }

        if (opts.json) {
          console.log(JSON.stringify(entity, null, 2))
        } else {
          Output.success(`Created ${chalk.bold(type)}: ${chalk.cyan(entity.title)} (${chalk.gray(entity.id)})`)
          if (edges.length > 0) {
            console.log(chalk.gray(`  Links: ${edges.map((e) => `${e.relation} → ${e.target}`).join(', ')}`))
          }
        }
      } catch (error) {
        handleError(error)
      }
    })

  // --- update ---
  kb.command('update <id>')
    .description('Update an entity')
    .option('-s, --status <status>', 'New status')
    .option('--title <title>', 'New title')
    .option('-p, --property <kv...>', 'Properties as key=value pairs')
    .option('-t, --tag <tags...>', 'Add tags')
    .option('--remove-tag <tags...>', 'Remove tags')
    .option('--strict', 'Reject on validation errors')
    .option('--draft', 'Allow validation issues (default)')
    .option('--actor <actor>', 'Actor for the event log (default: cli)')
    .option('--json', 'Output as JSON')
    .action(async (id, opts) => {
      try {
        const manager = getKB(opts)
        if (!requireInit(manager)) return

        const entity = await manager.updateEntity(id, {
          status: opts.status,
          title: opts.title,
          properties: opts.property ? parseProperties(opts.property) : undefined,
          addTags: opts.tag,
          removeTags: opts.removeTag,
          actor: opts.actor,
        })

        if (opts.json) {
          console.log(JSON.stringify(entity, null, 2))
        } else {
          Output.success(`Updated: ${chalk.cyan(entity.title)} (${chalk.gray(entity.id)}) → status: ${entity.status}`)
        }
      } catch (error) {
        handleError(error)
      }
    })

  // --- link ---
  kb.command('link <source> <relation> <target>')
    .description('Create a relationship between entities')
    .option('--strict', 'Reject on validation errors')
    .option('--draft', 'Allow validation issues (default)')
    .option('--actor <actor>', 'Actor for the event log (default: cli)')
    .option('-q, --qualifier <kv...>', 'Edge qualifiers as key=value (e.g. role=reviewer confidence=0.8)')
    .option('--note <text>', 'Short freeform note attached to the edge')
    .option('--confidence <n>', 'Confidence in this edge (0..1)')
    .option('--role <role>', 'Role qualifier (e.g. "reviewer", "owner")')
    .action(async (source, relation, target, opts) => {
      try {
        const manager = getKB(opts)
        if (!requireInit(manager)) return

        const qualifiers: Record<string, unknown> = {}
        if (opts.qualifier) {
          for (const kv of opts.qualifier) {
            const [k, ...rest] = kv.split('=')
            qualifiers[k] = rest.join('=')
          }
        }
        if (opts.note) qualifiers.note = opts.note
        if (opts.role) qualifiers.role = opts.role
        if (opts.confidence != null) {
          const n = Number(opts.confidence)
          if (!Number.isNaN(n)) qualifiers.confidence = n
        }

        await manager.addEdge(source, relation, target, opts.actor || 'cli', {
          qualifiers: Object.keys(qualifiers).length > 0 ? qualifiers : undefined,
        })
        Output.success(`Linked: ${chalk.cyan(source)} —[${chalk.yellow(relation)}]→ ${chalk.cyan(target)}`)
        if (Object.keys(qualifiers).length > 0) {
          console.log(chalk.gray(`  qualifiers: ${JSON.stringify(qualifiers)}`))
        }
      } catch (error) {
        handleError(error)
      }
    })

  // --- types ---
  kb.command('types')
    .description('Show the type registry — valid types, their prefixes and statuses')
    .option('--json', 'Output as JSON')
    .action((opts) => {
      try {
        if (opts.json) {
          console.log(JSON.stringify({
            types: KB_TYPES,
            prefixes: KB_TYPE_PREFIXES,
            statuses: KB_STATUSES,
            tiers: {
              work: KB_WORK_TYPES,
              knowledge: KB_KNOWLEDGE_TYPES,
              reference: KB_REFERENCE_TYPES,
            },
          }, null, 2))
          return
        }

        const tiers: Array<[string, KBTypeStrict[]]> = [
          ['Work', KB_WORK_TYPES],
          ['Knowledge', KB_KNOWLEDGE_TYPES],
          ['Reference', KB_REFERENCE_TYPES],
          ['Provenance', ['activity']],
        ]

        for (const [tier, types] of tiers) {
          console.log()
          console.log(chalk.bold.cyan(`  ${tier} tier:`))
          for (const t of types) {
            const prefix = KB_TYPE_PREFIXES[t]
            const statuses = KB_STATUSES[t].join(', ')
            console.log(`    ${chalk.bold(t.padEnd(12))} ${chalk.gray(`${prefix}-`)}  ${chalk.gray(statuses)}`)
          }
        }
        console.log()
      } catch (error) {
        handleError(error)
      }
    })

  // --- reclassify (change entity tier/type with full id migration) ---
  kb.command('reclassify <id> <newType>')
    .description('Reclassify an entity to a new type — changes the id prefix and migrates all referencing edges')
    .option('--json', 'Output result as JSON')
    .action(async (id, newType, opts) => {
      try {
        const manager = getKB()
        if (!requireInit(manager)) return

        const { KBMigrator } = await import('../../core/kb-migrator')
        const migrator = new KBMigrator(manager, process.cwd())

        const result = await migrator.reclassify(id, newType)

        if (opts.json) {
          console.log(JSON.stringify(result, null, 2))
          return
        }

        if (result.sameId) {
          Output.info(`No-op: entity ${chalk.cyan(id)} already has type ${chalk.yellow(newType)}`)
          return
        }
        Output.success(`Reclassified: ${chalk.gray(id)} → ${chalk.green(result.newId)}`)
        console.log(chalk.gray(`  Type: ${newType}`))
        console.log(chalk.gray(`  Edges updated: ${result.edgesUpdated}`))
        Output.info(`Run 'orka kb sync' to refresh views.`)
      } catch (error) {
        handleError(error)
      }
    })

  // --- upgrade (v1 → v2 migration) ---
  kb.command('upgrade')
    .description('Migrate a v1 KB to v2 schema (types, statuses, relations, qualifiers)')
    .option('--dry-run', 'Compute the plan without applying')
    .option('--apply', 'Apply the migration (backup is taken automatically)')
    .option('--json', 'Output the plan as JSON')
    .action(async (opts) => {
      try {
        const manager = getKB()
        if (!requireInit(manager)) return

        const { KBMigrator } = await import('../../core/kb-migrator')
        const migrator = new KBMigrator(manager, process.cwd())

        const plan = await migrator.computePlan()

        if (opts.json) {
          console.log(JSON.stringify(plan, null, 2))
          return
        }

        console.log()
        console.log(chalk.bold.cyan(`  Migration plan — ${plan.actions.length} action(s) across ${plan.totalEntities} entities:`))
        for (const [kind, count] of Object.entries(plan.byKind).sort((a, b) => b[1] - a[1])) {
          console.log(`    ${chalk.yellow(kind.padEnd(28))} ${count}`)
        }

        if (plan.actions.length === 0) {
          Output.success('\n  KB already on v2 — no migration needed.')
          return
        }

        // Show first 5 examples per kind
        console.log(chalk.bold('\n  Sample actions:'))
        const seen: Record<string, number> = {}
        for (const a of plan.actions) {
          seen[a.kind] = (seen[a.kind] || 0) + 1
          if (seen[a.kind] > 3) continue
          console.log(`    ${chalk.gray(a.entityId)} ${chalk.yellow(a.kind)}`)
          console.log(`      ${chalk.gray(a.reason)}`)
        }

        if (!opts.apply) {
          console.log()
          console.log(chalk.bold('  Dry-run only. To apply:'))
          console.log(chalk.green('    orka kb upgrade --apply'))
          console.log(chalk.gray('  A backup of events.jsonl will be created first.'))
          console.log()
          return
        }

        // Apply
        Output.info('\nBacking up events.jsonl...')
        const backup = await migrator.backup()
        console.log(chalk.gray(`  Backup: ${backup}`))

        Output.info('Applying migration...')
        const result = await migrator.apply(plan)

        console.log()
        console.log(chalk.bold.green(`  ✓ Migration complete`))
        console.log(`    Applied: ${chalk.bold(String(result.applied))}`)
        console.log(`    Failed:  ${chalk.bold(String(result.failed))}`)
        console.log(`    Events emitted: ${chalk.bold(String(result.events))}`)
        console.log()
        Output.info(`Run 'orka kb sync' to rebuild views, then 'orka kb lint' to verify.`)
        console.log()
      } catch (error) {
        handleError(error)
      }
    })

  // --- lint ---
  kb.command('lint')
    .description('Audit the KB for missing source, missing description, off-spec statuses, deprecated relations')
    .option('--type <type>', 'Filter to a specific entity type')
    .option('--fix', 'Apply automatic fixes where safe (status normalization)')
    .option('--json', 'Output as JSON')
    .action(async (opts) => {
      try {
        const manager = getKB()
        if (!requireInit(manager)) return

        const all = await manager.listEntities(opts.type ? { type: opts.type } : undefined)

        type Issue = { id: string; type: string; title: string; rule: string; detail: string }
        const issues: Issue[] = []

        const KB_REQ = (await import('../../models')).KB_REQUIRED_PROPERTIES as Record<string, readonly string[]>
        const KB_REC = (await import('../../models')).KB_RECOMMENDED_PROPERTIES as Record<string, readonly string[]>
        const REL = (await import('../../models')).KB_RELATIONS as Record<string, { deprecated?: boolean; migrationHint?: string }>
        const TYPE_LIST = (await import('../../models')).KB_TYPES as readonly string[]
        const STATUSES = (await import('../../models')).KB_STATUSES as Record<string, readonly string[]>

        for (const e of all) {
          // unknown type
          if (!TYPE_LIST.includes(e.type)) {
            issues.push({
              id: e.id, type: e.type, title: e.title,
              rule: 'unknown_type',
              detail: `Type "${e.type}" not in v2 registry — run 'orka kb upgrade' to migrate`,
            })
            continue // skip status check if type is unknown
          }

          // off-spec status
          const allowedStatuses = STATUSES[e.type] || []
          if (allowedStatuses.length > 0 && !allowedStatuses.includes(e.status)) {
            issues.push({
              id: e.id, type: e.type, title: e.title,
              rule: 'invalid_status',
              detail: `Status "${e.status}" not allowed for type "${e.type}"; valid: ${allowedStatuses.join(', ')}`,
            })
          }

          // missing required properties
          const required = KB_REQ[e.type] || []
          for (const prop of required) {
            const v = e.properties[prop]
            if (v === undefined || v === null || (typeof v === 'string' && !v.trim())) {
              issues.push({
                id: e.id, type: e.type, title: e.title,
                rule: 'missing_required',
                detail: `Required property "${prop}" is missing or empty`,
              })
            }
          }

          // missing recommended properties (warnings)
          const recommended = KB_REC[e.type] || []
          for (const prop of recommended) {
            if (!(prop in e.properties)) {
              issues.push({
                id: e.id, type: e.type, title: e.title,
                rule: 'missing_recommended',
                detail: `Recommended property "${prop}" not set`,
              })
            }
          }

          // missing source/provenance — entities should have at least one
          const hasSource = !!(e.properties.source_path || e.properties.source) ||
            e.edges.some((edge) => edge.relation === 'sourced-from' || edge.relation === 'generated-by' || edge.relation === 'derived-from')
          // Person/repo/activity don't need source provenance
          if (!hasSource && !['person', 'repo', 'activity', 'goal'].includes(e.type)) {
            issues.push({
              id: e.id, type: e.type, title: e.title,
              rule: 'missing_source',
              detail: `No source_path, source property, or sourced-from/generated-by edge`,
            })
          }

          // deprecated relations
          for (const edge of e.edges) {
            const def = REL[edge.relation]
            if (def?.deprecated) {
              issues.push({
                id: e.id, type: e.type, title: e.title,
                rule: 'deprecated_relation',
                detail: `Edge "${edge.relation} → ${edge.target}" uses deprecated relation; ${def.migrationHint || 'migrate to typed relation'}`,
              })
            }
          }
        }

        if (opts.json) {
          console.log(JSON.stringify(issues, null, 2))
          return
        }

        if (issues.length === 0) {
          Output.success(`KB lint passed — ${all.length} entities checked, no issues found`)
          return
        }

        // Summary by rule
        const byRule: Record<string, number> = {}
        for (const i of issues) byRule[i.rule] = (byRule[i.rule] || 0) + 1

        console.log()
        console.log(chalk.bold.cyan(`  Lint summary — ${issues.length} issue(s) across ${all.length} entities:`))
        for (const [rule, count] of Object.entries(byRule).sort((a, b) => b[1] - a[1])) {
          console.log(`    ${chalk.yellow(rule.padEnd(22))} ${count}`)
        }

        // Top offenders by entity
        const byEntity: Record<string, Issue[]> = {}
        for (const i of issues) {
          if (!byEntity[i.id]) byEntity[i.id] = []
          byEntity[i.id].push(i)
        }
        const topOffenders = Object.entries(byEntity)
          .sort((a, b) => b[1].length - a[1].length)
          .slice(0, 10)

        console.log(chalk.bold('\n  Top offenders:'))
        for (const [id, list] of topOffenders) {
          const e = list[0]
          console.log(`    ${chalk.gray(id)} ${chalk.bold(e.title.slice(0, 60))} ${chalk.gray(`[${e.type}]`)}`)
          for (const i of list.slice(0, 3)) {
            console.log(`      ${chalk.yellow(i.rule)}: ${chalk.gray(i.detail.slice(0, 100))}`)
          }
        }
        console.log(chalk.gray('\n  Run with --json for full output, or --type <type> to scope by entity type.'))
        console.log()
      } catch (error) {
        handleError(error)
      }
    })

  // --- classify ---
  kb.command('classify <id>')
    .description('Suggest a tier reclassification for an entity (heuristic-based)')
    .option('--json', 'Output as JSON')
    .action(async (id, opts) => {
      try {
        const manager = getKB()
        if (!requireInit(manager)) return

        const entity = await manager.getEntity(id)
        if (!entity) {
          Output.error(`Entity not found: ${id}`)
          return
        }

        const allEntities = await manager.listEntities()
        const incomingEdges = allEntities.filter((e) =>
          e.edges.some((edge) => edge.target === id)
        ).length

        const suggestion = classifyEntity(entity, incomingEdges)

        if (opts.json) {
          console.log(JSON.stringify(suggestion, null, 2))
          return
        }

        console.log()
        console.log(chalk.bold.cyan(`  Classification suggestion for ${chalk.cyan(entity.id)}`))
        console.log(`  Title: ${entity.title}`)
        console.log(`  Current type: ${chalk.yellow(entity.type)}`)
        if (suggestion.suggestedType === entity.type) {
          console.log(`  ${chalk.green('✓')} Current classification looks correct.`)
        } else {
          console.log(`  ${chalk.bold('Suggested:')} ${chalk.green(suggestion.suggestedType)}`)
          console.log(`  ${chalk.bold('Confidence:')} ${suggestion.confidence}`)
        }
        console.log(chalk.bold('\n  Reasoning:'))
        for (const reason of suggestion.reasons) {
          console.log(`    • ${reason}`)
        }
        if (suggestion.suggestedType !== entity.type) {
          console.log(chalk.gray('\n  Reclassification is destructive (changes id prefix and migrates edges).'))
          console.log(chalk.gray(`  Run 'orka kb upgrade' (P9 migration) to apply tier changes safely.`))
        }
        console.log()
      } catch (error) {
        handleError(error)
      }
    })

  // --- skills sync ---
  kb.command('skills-sync')
    .description('Re-install / update Claude Code skills in .claude/skills/ from the current Orka package version')
    .option('--dry-run', 'Show what would change without writing')
    .option('--diff', 'Show a content-diff summary per skill')
    .action(async (opts) => {
      try {
        const projectPath = process.cwd()
        const skillsDir = path.join(projectPath, '.claude', 'skills')
        const skillsSource = getSkillsSourcePath()

        if (!skillsSource) {
          Output.error('Skills source not found in package — install Orka with: npm install -g @enruana/claude-orka')
          return
        }

        await fs.ensureDir(skillsDir)

        // Enumerate source skills — directory format is preferred (each
        // dir is <name>/SKILL.md), but a stray flat .md file at the top
        // level of the source is still supported.
        const sourceEntries = await fs.readdir(skillsSource, { withFileTypes: true })
        type SourceSkill = { name: string; kind: 'dir' | 'file'; path: string }
        const sourceSkills: SourceSkill[] = []
        for (const e of sourceEntries) {
          if (e.isDirectory()) {
            sourceSkills.push({ name: e.name, kind: 'dir', path: path.join(skillsSource, e.name) })
          } else if (e.isFile() && e.name.endsWith('.md')) {
            sourceSkills.push({
              name: e.name.replace(/\.md$/, ''),
              kind: 'file',
              path: path.join(skillsSource, e.name),
            })
          }
        }
        const sourceNames = new Set(sourceSkills.map((s) => s.name))

        // Enumerate the project's current skills — both dirs and flat.
        // Track flat legacy files matching a name we now ship as a dir so
        // we clean them up on apply (Claude Code would otherwise index
        // ambiguously).
        const destEntries = await fs.pathExists(skillsDir)
          ? await fs.readdir(skillsDir, { withFileTypes: true })
          : []
        const destDirNames = new Set(destEntries.filter((e) => e.isDirectory()).map((e) => e.name))
        const destFileNames = new Set(
          destEntries.filter((e) => e.isFile() && e.name.endsWith('.md')).map((e) => e.name)
        )

        const toAdd: string[] = []
        const toUpdate: string[] = []
        const toMigrate: string[] = [] // legacy flat file for a name we now ship as a directory
        const orphan: string[] = []

        for (const s of sourceSkills) {
          if (s.kind === 'dir') {
            const destDir = path.join(skillsDir, s.name)
            const hasDir = destDirNames.has(s.name)
            const hasLegacy = destFileNames.has(`${s.name}.md`)
            if (!hasDir && !hasLegacy) {
              toAdd.push(s.name)
            } else if (!hasDir && hasLegacy) {
              // Legacy flat file for a skill that's now a directory —
              // needs migration regardless of content diff.
              toMigrate.push(s.name)
            } else if (await directoriesDiffer(s.path, destDir)) {
              toUpdate.push(s.name)
              if (hasLegacy) toMigrate.push(s.name)
            } else if (hasLegacy) {
              toMigrate.push(s.name)
            }
          } else {
            // Flat file source (rare — kept for one-off skills).
            const destFile = path.join(skillsDir, `${s.name}.md`)
            if (!destFileNames.has(`${s.name}.md`)) {
              toAdd.push(s.name)
              continue
            }
            const [srcContent, destContent] = await Promise.all([
              fs.readFile(s.path, 'utf-8'),
              fs.readFile(destFile, 'utf-8'),
            ])
            if (srcContent !== destContent) toUpdate.push(s.name)
          }
        }

        // Orphan detection: any kb-* / board-* left in the project that
        // no source skill claims. Directory or flat, both surface.
        const managedPrefixes = ['kb-', 'board-']
        const isManaged = (n: string) => managedPrefixes.some((p) => n.startsWith(p))
        for (const name of destDirNames) {
          if (!sourceNames.has(name) && isManaged(name)) orphan.push(name)
        }
        for (const file of destFileNames) {
          const base = file.replace(/\.md$/, '')
          if (!sourceNames.has(base) && isManaged(base)) orphan.push(file)
        }

        // Print plan
        console.log()
        console.log(chalk.bold.cyan('  Skills sync plan:'))
        console.log(`    ${chalk.green('+ add:')}    ${toAdd.length} new skill${toAdd.length !== 1 ? 's' : ''} ${toAdd.length > 0 ? chalk.gray(toAdd.join(', ')) : ''}`)
        console.log(`    ${chalk.yellow('~ update:')} ${toUpdate.length} changed skill${toUpdate.length !== 1 ? 's' : ''} ${toUpdate.length > 0 ? chalk.gray(toUpdate.join(', ')) : ''}`)
        if (toMigrate.length > 0) {
          console.log(`    ${chalk.magenta('↳ migrate:')} ${toMigrate.length} legacy flat file${toMigrate.length !== 1 ? 's' : ''} → directory format ${chalk.gray(toMigrate.join(', '))}`)
        }
        if (orphan.length > 0) {
          console.log(`    ${chalk.gray('orphan:')}  ${orphan.length} skill${orphan.length !== 1 ? 's' : ''} present in your folder but no longer in the package: ${chalk.gray(orphan.join(', '))}`)
        }

        if (opts.diff) {
          for (const name of toUpdate) {
            const src = sourceSkills.find((s) => s.name === name)!
            const isDir = src.kind === 'dir'
            const srcSkillMd = isDir ? path.join(src.path, 'SKILL.md') : src.path
            const destSkillMd = isDir
              ? path.join(skillsDir, name, 'SKILL.md')
              : path.join(skillsDir, `${name}.md`)
            if (!(await fs.pathExists(srcSkillMd)) || !(await fs.pathExists(destSkillMd))) continue
            const [s, d] = await Promise.all([
              fs.readFile(srcSkillMd, 'utf-8'),
              fs.readFile(destSkillMd, 'utf-8'),
            ])
            const sL = s.split('\n').length
            const dL = d.split('\n').length
            console.log(chalk.gray(`      ${name}: ${dL}L → ${sL}L (${sL - dL >= 0 ? '+' : ''}${sL - dL})`))
          }
        }

        if (toAdd.length === 0 && toUpdate.length === 0 && toMigrate.length === 0) {
          console.log()
          Output.success('Skills already up to date.')
          return
        }

        if (opts.dryRun) {
          console.log()
          Output.info('Dry-run only. To apply: orka kb skills-sync')
          return
        }

        // Apply
        let applied = 0
        const touched = new Set<string>([...toAdd, ...toUpdate, ...toMigrate])
        for (const name of touched) {
          const src = sourceSkills.find((s) => s.name === name)
          if (!src) continue
          if (src.kind === 'dir') {
            await fs.copy(src.path, path.join(skillsDir, name), { overwrite: true })
            // Clean up any legacy flat file with the same base name.
            const legacyFlat = path.join(skillsDir, `${name}.md`)
            if (await fs.pathExists(legacyFlat)) await fs.remove(legacyFlat)
          } else {
            await fs.copy(src.path, path.join(skillsDir, `${name}.md`), { overwrite: true })
          }
          applied++
        }
        console.log()
        Output.success(`Synced ${applied} skill${applied !== 1 ? 's' : ''} to .claude/skills/`)
        if (orphan.length > 0) {
          Output.info(`Orphan skills (${orphan.join(', ')}) left untouched. Delete manually if you want them gone.`)
        }
      } catch (error) {
        handleError(error)
      }
    })

  // --- relations ---
  kb.command('relations')
    .description('Show the relation vocabulary with type constraints')
    .option('--json', 'Output as JSON')
    .action((opts) => {
      try {
        if (opts.json) {
          console.log(JSON.stringify(KB_RELATIONS, null, 2))
          return
        }

        const grouped: Record<string, string[]> = {
          'Hierarchy': ['subtask-of', 'scope-of', 'child-of'],
          'Knowledge ↔ work': ['addresses', 'answers', 'implements'],
          'Knowledge ↔ meeting': ['decided-at', 'raised-at', 'attended-by'],
          'Lifecycle': ['blocks', 'depends-on', 'supersedes'],
          'Provenance (PROV-O)': ['sourced-from', 'generated-by', 'derived-from', 'attributed-to'],
          'Categorical': ['relates-to', 'assigned-to', 'references', 'owned-by'],
          'Deprecated': Object.entries(KB_RELATIONS).filter(([, d]) => d.deprecated).map(([k]) => k),
        }

        for (const [group, names] of Object.entries(grouped)) {
          if (names.length === 0) continue
          console.log()
          console.log(chalk.bold.cyan(`  ${group}:`))
          for (const name of names) {
            const def = KB_RELATIONS[name]
            if (!def) continue
            const sources = def.source === '*' ? '*' : def.source.join('|')
            const targets = def.target === '*' ? '*' : def.target.join('|')
            const dep = def.deprecated ? chalk.red(' [deprecated]') : ''
            console.log(`    ${chalk.yellow(name.padEnd(18))} ${chalk.gray(`${sources} → ${targets}`)}${dep}`)
            console.log(`      ${chalk.gray(def.description)}`)
            if (def.migrationHint) {
              console.log(`      ${chalk.yellow('Migrate:')} ${chalk.gray(def.migrationHint)}`)
            }
          }
        }
        console.log()
      } catch (error) {
        handleError(error)
      }
    })

  // --- show ---
  kb.command('show <id>')
    .description('Display an entity with its edges')
    .option('--json', 'Output as JSON')
    .action(async (id, opts) => {
      try {
        const manager = getKB()
        if (!requireInit(manager)) return

        const entity = await manager.getEntity(id)
        if (!entity) {
          Output.error(`Entity not found: ${id}`)
          return
        }

        if (opts.json) {
          console.log(JSON.stringify(entity, null, 2))
          return
        }

        console.log()
        console.log(chalk.bold.cyan(`  ${entity.title}`))
        console.log(chalk.gray(`  ${entity.id} | ${entity.type} | ${entity.status}`))
        console.log(chalk.gray(`  Created: ${entity.created.split('T')[0]} | Updated: ${entity.updated.split('T')[0]}`))

        if (entity.tags.length > 0) {
          console.log(`  Tags: ${entity.tags.map((t) => chalk.yellow(`#${t}`)).join(' ')}`)
        }

        if (Object.keys(entity.properties).length > 0) {
          console.log(chalk.bold('\n  Properties:'))
          for (const [key, value] of Object.entries(entity.properties)) {
            console.log(`    ${chalk.white(key)}: ${chalk.gray(String(value))}`)
          }
        }

        if (entity.edges.length > 0) {
          console.log(chalk.bold('\n  Relationships:'))
          for (const edge of entity.edges) {
            const date = (edge.qualifiers?.at || edge.since || '').split('T')[0]
            const by = edge.qualifiers?.by ? ` by ${edge.qualifiers.by}` : ''
            console.log(`    → ${chalk.yellow(edge.relation)} → ${chalk.cyan(edge.target)} ${chalk.gray(`(${date}${by})`)}`)
            const q = edge.qualifiers
            if (q) {
              const extras: string[] = []
              if (q.role) extras.push(`role: ${q.role}`)
              if (q.confidence !== undefined) extras.push(`confidence: ${q.confidence}`)
              if (q.note) extras.push(`note: ${q.note}`)
              if (extras.length > 0) {
                console.log(`      ${chalk.gray(extras.join(' | '))}`)
              }
            }
          }
        }

        if (entity.history.length > 0) {
          console.log(chalk.bold('\n  History:'))
          for (const h of entity.history.slice(-5)) {
            console.log(`    ${chalk.gray(h.ts.split('T')[0])} ${h.summary}`)
          }
        }

        console.log()
      } catch (error) {
        handleError(error)
      }
    })

  // --- list ---
  kb.command('list')
    .description('List entities')
    .option('--type <type>', 'Filter by type')
    .option('--status <status>', 'Filter by status')
    .option('--tag <tag>', 'Filter by tag')
    .option('--json', 'Output as JSON')
    .action(async (opts) => {
      try {
        const manager = getKB()
        if (!requireInit(manager)) return

        const entities = await manager.listEntities({
          type: opts.type,
          status: opts.status,
          tag: opts.tag,
        })

        if (opts.json) {
          console.log(JSON.stringify(entities, null, 2))
          return
        }

        if (entities.length === 0) {
          Output.info('No entities found')
          return
        }

        console.log(chalk.bold.cyan(`\n  Entities (${entities.length}):\n`))
        for (const e of entities) {
          const tags = e.tags.length > 0 ? chalk.yellow(` [${e.tags.join(', ')}]`) : ''
          const status = e.status !== 'active' ? chalk.gray(` (${e.status})`) : ''
          console.log(`  ${chalk.gray(e.id)} ${chalk.bold(e.title)}${status}${tags}`)
          console.log(`    ${chalk.gray(`${e.type} | updated ${e.updated.split('T')[0]} | ${e.edges.length} links`)}`)
        }
        console.log()
      } catch (error) {
        handleError(error)
      }
    })

  // --- history ---
  kb.command('history <id>')
    .description('Show event history for an entity')
    .action(async (id) => {
      try {
        const manager = getKB()
        if (!requireInit(manager)) return

        const events = await manager.getEntityHistory(id)

        if (events.length === 0) {
          Output.info(`No events found for: ${id}`)
          return
        }

        console.log(chalk.bold.cyan(`\n  History for ${id}:\n`))
        for (const evt of events) {
          const date = evt.ts.split('T')[0]
          const time = evt.ts.split('T')[1]?.slice(0, 5) || ''
          console.log(`  ${chalk.gray(`${date} ${time}`)} ${chalk.white(evt.type)} ${chalk.gray(`(${evt.actor})`)}`)
        }
        console.log()
      } catch (error) {
        handleError(error)
      }
    })

  // --- timeline ---
  kb.command('timeline')
    .description('Show event timeline')
    .option('--since <date>', 'Show events since date (YYYY-MM-DD)')
    .option('--limit <n>', 'Limit number of events', '30')
    .action(async (opts) => {
      try {
        const manager = getKB()
        if (!requireInit(manager)) return

        const events = await manager.getTimeline({
          since: opts.since,
          limit: parseInt(opts.limit, 10),
        })

        if (events.length === 0) {
          Output.info('No events found')
          return
        }

        console.log(chalk.bold.cyan(`\n  Timeline (${events.length} events):\n`))
        let currentDate = ''
        for (const evt of events) {
          const date = evt.ts.split('T')[0]
          if (date !== currentDate) {
            currentDate = date
            console.log(chalk.bold(`\n  ${date}`))
          }
          const time = evt.ts.split('T')[1]?.slice(0, 5) || ''
          const entity = evt.entityId ? chalk.cyan(` ${evt.entityId}`) : ''
          console.log(`    ${chalk.gray(time)} ${evt.type}${entity}`)
        }
        console.log()
      } catch (error) {
        handleError(error)
      }
    })

  // --- graph ---
  kb.command('graph')
    .description('Export knowledge graph')
    .option('--format <format>', 'Output format: dot or json', 'dot')
    .action(async (opts) => {
      try {
        const manager = getKB()
        if (!requireInit(manager)) return

        const output = await manager.exportGraph(opts.format)
        console.log(output)
      } catch (error) {
        handleError(error)
      }
    })

  // --- context ---
  kb.command('context')
    .description('Output AI-optimized project context')
    .option('--project <id>', 'Filter context to a specific project entity')
    .option('--breadth <b>', 'Traversal breadth: narrow | medium | wide', 'medium')
    .action(async (opts) => {
      try {
        const manager = getKB()
        if (!requireInit(manager)) return

        const breadth = (['narrow', 'medium', 'wide'].includes(opts.breadth) ? opts.breadth : 'medium') as 'narrow' | 'medium' | 'wide'
        const context = await manager.generateContext(opts.project, breadth)
        console.log(context)
      } catch (error) {
        handleError(error)
      }
    })

  // --- project-doc ---
  kb.command('project-doc <id>')
    .description('Generate or update the master INDEX.md for a project')
    .option('--breadth <b>', 'Traversal breadth: narrow | medium | wide', 'medium')
    .action(async (id, opts) => {
      try {
        const manager = getKB()
        if (!requireInit(manager)) return

        const breadth = (['narrow', 'medium', 'wide'].includes(opts.breadth) ? opts.breadth : 'medium') as 'narrow' | 'medium' | 'wide'
        const { filePath } = await manager.generateProjectDoc(id, breadth)
        Output.success(`Project index updated: ${chalk.cyan(filePath)}`)
      } catch (error) {
        handleError(error)
      }
    })

  // --- sync ---
  kb.command('sync')
    .description('Rebuild entities and views from event log')
    .action(async () => {
      try {
        const manager = getKB()
        if (!requireInit(manager)) return

        await manager.sync()
        Output.success('Knowledge Base synced — entities and views rebuilt from events')
      } catch (error) {
        handleError(error)
      }
    })

  // --- migrate ---
  kb.command('migrate')
    .description('Bootstrap KB from existing project (git, docs)')
    .action(async () => {
      try {
        const manager = getKB()

        if (!manager.isInitialized()) {
          await manager.initialize()
          Output.success('Knowledge Base initialized')
        }

        Output.info('Analyzing project...')
        const events = await manager.migrate()
        Output.success(`Migration complete — created ${events.length} entities from project analysis`)
      } catch (error) {
        handleError(error)
      }
    })

  // --- ingest ---
  kb.command('ingest <file>')
    .description('Parse a file and extract entities (basic structural parsing)')
    .action(async (file) => {
      try {
        const manager = getKB()
        if (!requireInit(manager)) return

        const fullPath = path.resolve(file)
        if (!await fs.pathExists(fullPath)) {
          Output.error(`File not found: ${file}`)
          return
        }

        // Create artifact entity referencing the file
        const entity = await manager.addEntity('artifact', path.basename(file), {
          properties: { filePath: fullPath, ingestedAt: new Date().toISOString() },
          tags: ['ingested'],
        })

        Output.success(`Ingested: ${chalk.cyan(path.basename(file))} → ${chalk.gray(entity.id)}`)
        Output.info('For AI-assisted parsing, use the /kb-ingest skill in Claude Code')
      } catch (error) {
        handleError(error)
      }
    })
}

// --- Classification heuristic ---

interface ClassifySuggestion {
  suggestedType: KBTypeStrict | string
  confidence: 'low' | 'medium' | 'high'
  reasons: string[]
}

/**
 * Heuristic to suggest a better tier for an entity. The signals come from:
 * - Title patterns (e.g., "ENG-1234" → likely a ticketed bug/task)
 * - Properties (target_release, deadline, repo_path, time_box)
 * - Description content (keywords like "team", "investigate", "fix")
 * - Graph topology (incoming edges, sub-entity count)
 *
 * Heuristics are intentionally explainable (each scoring rule emits a reason)
 * so the user can audit why a suggestion was made.
 */
function classifyEntity(
  entity: { id: string; type: string; title: string; properties: Record<string, unknown>; edges: { relation: string; target: string }[] },
  incomingEdgesCount: number
): ClassifySuggestion {
  const title = entity.title.toLowerCase()
  const desc = String(entity.properties.description || '').toLowerCase()
  const props = entity.properties
  const reasons: string[] = []
  const scores: Record<string, number> = {
    goal: 0,
    initiative: 0,
    project: 0,
    task: 0,
    spike: 0,
    bug: 0,
  }

  // --- Title patterns ---
  if (/\b(eng|jira|tkt|tic|bug|fix)-?\d+\b/i.test(entity.title)) {
    if (title.includes('bug') || title.includes('fix') || title.includes('error') || desc.includes('bug')) {
      scores.bug += 3
      reasons.push('Title looks like a ticket ID and references a bug/fix/error → bug')
    } else {
      scores.task += 2
      reasons.push('Title looks like a ticket ID → task')
    }
  }
  if (/^(spike|investigate|explore|research|prototype|proof of concept|poc)\b/i.test(entity.title)) {
    scores.spike += 3
    reasons.push('Title starts with investigative verb → spike')
  }
  if (/\b(epic|prd|workstream)\b/i.test(entity.title)) {
    scores.initiative += 2
    reasons.push('Title contains epic/PRD/workstream → initiative')
  }
  if (/\b(area|team|brain|ongoing|continuous)\b/i.test(title) || /\b(area|team|ongoing|continuous)\b/i.test(desc)) {
    scores.goal += 1
    reasons.push('Suggests an ongoing area/responsibility → goal')
  }

  // --- Property signals ---
  if (props.target_release || props.deadline || props.target) {
    scores.project += 2
    scores.initiative += 1
    reasons.push('Has target_release/deadline/target → bounded outcome (project or initiative)')
  }
  if (props.repo_path) {
    scores.project += 1
    reasons.push('Has repo_path → typically a project')
  }
  if (props.time_box) {
    scores.spike += 3
    reasons.push('Has time_box → spike')
  }
  if (props.estimate || props.story_points) {
    scores.task += 2
    reasons.push('Has estimate/story_points → atomic task')
  }
  if (props.severity || props.repro_steps || props.reporter) {
    scores.bug += 3
    reasons.push('Has severity/repro_steps/reporter → bug')
  }

  // --- Graph topology ---
  const childEdges = entity.edges.filter((e) => e.relation === 'part-of' || e.relation === 'subtask-of' || e.relation === 'scope-of').length
  if (incomingEdgesCount >= 5) {
    scores.project += 1
    scores.initiative += 1
    reasons.push(`Has ${incomingEdgesCount} incoming edges → likely a container (project/initiative)`)
  }
  if (incomingEdgesCount >= 10) {
    scores.initiative += 2
    reasons.push('Very large container (10+ links) → likely initiative')
  }
  if (childEdges === 0 && incomingEdgesCount === 0) {
    scores.task += 1
    reasons.push('Leaf entity with no children/incoming → atomic task')
  }

  // --- Description length signal ---
  if (desc.length > 0 && desc.length < 100) {
    scores.task += 0.5
  } else if (desc.length > 400) {
    scores.project += 0.5
    scores.initiative += 0.5
  }

  // Pick the winner
  const ranked = Object.entries(scores).sort((a, b) => b[1] - a[1])
  const [topType, topScore] = ranked[0]
  const [, secondScore] = ranked[1]
  const margin = topScore - secondScore

  // If no strong signal, respect the current type — heuristics shouldn't
  // bully entities that simply lack metadata yet.
  if (topScore < 2) {
    return {
      suggestedType: entity.type,
      confidence: 'low',
      reasons: reasons.length > 0 ? reasons : ['Insufficient signal to suggest reclassification'],
    }
  }

  let confidence: 'low' | 'medium' | 'high' = 'low'
  if (topScore >= 4 && margin >= 2) confidence = 'high'
  else if (topScore >= 2.5 && margin >= 1) confidence = 'medium'

  return {
    suggestedType: topType,
    confidence,
    reasons,
  }
}

// --- Helpers ---

function parseProperties(kvPairs: string[]): Record<string, unknown> {
  const props: Record<string, unknown> = {}
  for (const kv of kvPairs) {
    const [key, ...rest] = kv.split('=')
    props[key] = rest.join('=')
  }
  return props
}

async function installSkills(): Promise<void> {
  const projectPath = process.cwd()
  const skillsDir = path.join(projectPath, '.claude', 'skills')
  await fs.ensureDir(skillsDir)

  const skillsSource = getSkillsSourcePath()
  if (!skillsSource) {
    Output.warn('Skills source not found — skills not installed')
    return
  }

  // Support both directory-format skills (`<name>/SKILL.md` with
  // frontmatter — the discoverable form) and legacy flat `.md` files.
  const entries = await fs.readdir(skillsSource, { withFileTypes: true })
  let installedDirs = 0
  let installedFiles = 0
  let cleanedLegacy = 0

  for (const entry of entries) {
    if (entry.isDirectory()) {
      const src = path.join(skillsSource, entry.name)
      const dest = path.join(skillsDir, entry.name)
      await fs.copy(src, dest, { overwrite: true })
      installedDirs++

      // Remove any legacy flat file matching the same name — the two
      // would otherwise coexist and confuse Claude Code's discovery.
      const legacyFlat = path.join(skillsDir, `${entry.name}.md`)
      if (await fs.pathExists(legacyFlat)) {
        await fs.remove(legacyFlat)
        cleanedLegacy++
      }
    } else if (entry.isFile() && entry.name.endsWith('.md')) {
      const dest = path.join(skillsDir, entry.name)
      await fs.copy(path.join(skillsSource, entry.name), dest, { overwrite: true })
      installedFiles++
    }
  }

  const total = installedDirs + installedFiles
  if (total > 0) {
    const parts = [`${installedDirs} directory`, `${installedFiles} file`]
      .filter((_p, i) => (i === 0 ? installedDirs : installedFiles) > 0)
    Output.success(
      `Installed ${total} Claude Code skill${total !== 1 ? 's' : ''} (${parts.join(' + ')}) in .claude/skills/` +
      (cleanedLegacy ? ` — cleaned ${cleanedLegacy} legacy flat file${cleanedLegacy !== 1 ? 's' : ''}` : '')
    )
  } else {
    Output.info('Claude Code skills already installed')
  }
}

/**
 * Recursive equality check between two directories — used by
 * `skills-sync` to decide whether a directory-format skill needs
 * updating without shelling out to `diff`.
 */
async function directoriesDiffer(a: string, b: string): Promise<boolean> {
  const bExists = await fs.pathExists(b)
  const [aEntries, bEntries] = await Promise.all([
    fs.readdir(a, { withFileTypes: true }),
    bExists ? fs.readdir(b, { withFileTypes: true }) : Promise.resolve([] as any[]),
  ])
  const aNames = new Set(aEntries.map((e) => e.name))
  const bNames = new Set(bEntries.map((e: any) => e.name))
  if (aNames.size !== bNames.size) return true
  for (const name of aNames) {
    if (!bNames.has(name)) return true
    const aPath = path.join(a, name)
    const bPath = path.join(b, name)
    const [aStat, bStat] = await Promise.all([fs.stat(aPath), fs.stat(bPath)])
    if (aStat.isDirectory() !== bStat.isDirectory()) return true
    if (aStat.isDirectory()) {
      if (await directoriesDiffer(aPath, bPath)) return true
    } else {
      const [aContent, bContent] = await Promise.all([
        fs.readFile(aPath, 'utf-8'),
        fs.readFile(bPath, 'utf-8'),
      ])
      if (aContent !== bContent) return true
    }
  }
  return false
}
